export const SEACH_FOCUS= 'header/SEARCH_FOCUS'
export const SEACH_BLUR = 'header/SEARCH_BLUR'
export const CHANG_LIST =　'header/CHANGE_LIST'
export const MOUSEENTER = 'header/MOUSE_ENTER'
export const MOUSELEAVE = 'header/MOUSE_LEAVE'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'